# Generated by Django 5.1.6 on 2025-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                ("gene_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("lit_occurrences", models.IntegerField(blank=True, null=True)),
                (
                    "development_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("expression", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
